### ISSUE TITLE
Otherwise checking

### ISSUE THREAD

**Issue by chamini2** [joseluisjb1990/gacela#11]
I'm not sure if this is already done, but wanted to check with you:

Having a second `otherwise` should give a static error
```gcl
if r == 0 -> wrinteln("OK")
[] r == 1 -> writeln("Better!")
[] otherwise -> writeln("Nope")
[] otherwise -> writeln("And having a second otherwise should give a static error")
fi
```

And, an `otherwise` in the middle of the clauses should just run if all other clauses are `false`. 

```gcl
if r == 0 -> wrinteln("OK")
[] otherwise -> writeln("Should not run this")
[] r != 0 -> writeln("Correct output <-")
fi
```
By this I mean, it should not try options sequentially, but ignore the `otherwise` until all other clauses have been checked.

Maybe these both cases are already working, but wanted to bring it up.

**Comment by adgalad** [comment]
Fixed. Will be available in the next patch
