### ISSUE TITLE
double and float types inconsistency

### ISSUE THREAD

**Issue by chamini2** [joseluisjb1990/gacela#2]
When declaring new variables of floating point, e.g.:

```
var f : float
````

It works only with the type `float` (no type `double`). But if then I use the `f` variable with an `int` value, e.g.:

```
writeln(f - 5)
````

It errors about type `double`:

```
Temperatura.gcl:11:11: Error:
	Operator `(-)` at  (line 11, (col 13 -> col 14)) received two expressions of types:
		(double,int)
	but expected an expression of type
		(int,int), (char,char), or (double,double)
```

**Comment by akrmn** [comment]
Thanks, fixed in 2.0.1
