### ISSUE TITLE
Lexer error when string is not closed

### ISSUE THREAD

**Issue by chamini2** [joseluisjb1990/gacela#4]
When parsing a program like

```
program Hello begin
main |[ writeln("Hello world!) ]|
end
```

It throws the following errorL

> graciela: internal error: uncaught unexpected token

Maybe *non-closed-strings* should be considered as a special case of error, to give a good report.

Maybe something like:

```
Hello.gcl:2:17: Error:
    Found never ending string
```

**Comment by adgalad** [comment]
Fixed
