### ISSUE TITLE
Compiler misbehaviour when inputting a non-integer value at an integer-variable read instruction

### ISSUE THREAD

**Issue by aitorres** [joseluisjb1990/gacela#9]
Consider the following program:

program Boolean begin

```
program Boolean begin

main
|[
	var a : int
  ; var b : boolean
  ; read(a)
  ; read(b)
]|
end
```

If I input a non-integer character in the first read (when reading variable 'a'), the program outputs an error regarding the next read. This is the output (the explanation I've found is given below)

```
 aitorres@fibonacci:~/lab$ rungraciela boolean.gcl 
t
Error: The value read from file is not of type boolean

```

I've found that, in a longer, more complex program (which I can give, if more information is needed to further replicate the problem) that starts with reading an integer variable, **if I input a non-integer input, the program just runs completely and skips absolutely all the read instructions.** The problem comes when Graciela finds a read instruction for a boolean variable. I think the compiler should output an error if/when a non-integer value is tried to be read as an integer and abort the execution of the remaining code, therefore avoiding any other problem that might come if the program is ran without any effective inputs.

Note that this problem does not _neccessarily_ affect the current project on Universidad Simón Bolívar's CI-2691, but it might come as an error anyway.

**Comment by adgalad** [comment]
Thanks for your feedback @andresitorresm. I've improve the read function and its verifications. As you said, when reading an integer or a float variable, you could input a string with non-numeric symbols. It is not longer legal.

Now, when reading a boolean, only "1", "0", "true", "false" are valid inputs.

Floats and ints now throw an error if what it'd read is **not really** a float or and integer
